<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\AiTool;
use Illuminate\Database\Seeder;

class AiToolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoriesData = [
            [
                'name' => 'Coding & Development',
                'name_th' => 'เขียนโค้ด & พัฒนาโปรแกรม',
                'slug' => 'coding',
                'icon' => 'code',
                'description' => 'เครื่องมือ AI ช่วยเขียนโค้ด ตรวจบั๊ก สร้างเว็บไซต์ และพัฒนาแอปพลิเคชัน',
                'order' => 1,
            ],
            [
                'name' => 'Image & Art Design',
                'name_th' => 'สร้างภาพ & งานกราฟิก',
                'slug' => 'image',
                'icon' => 'image',
                'description' => 'AI เจนภาพถ่าย ภาพวาด กราฟิกดีไซน์ และปรับแต่งรูปภาพอัจฉริยะ',
                'order' => 2,
            ],
            [
                'name' => 'Video & Animation',
                'name_th' => 'สร้าง & ตัดต่อวิดีโอ',
                'slug' => 'video',
                'icon' => 'video',
                'description' => 'AI สร้างวิดีโอจากข้อความ แปลงภาพนิ่งเป็นแอนิเมชัน และตัดต่ออัตโนมัติ',
                'order' => 3,
            ],
            [
                'name' => 'Voice & Music',
                'name_th' => 'เสียงพากย์ & แต่งเพลง',
                'slug' => 'audio',
                'icon' => 'mic',
                'description' => 'AI โคลนนิ่งเสียง แปลงข้อความเป็นเสียงพากย์สมจริง และแต่งเพลงครบวงจร',
                'order' => 4,
            ],
            [
                'name' => 'Writing & Marketing',
                'name_th' => 'เขียนบทความ & การตลาด',
                'slug' => 'writing',
                'icon' => 'pen-tool',
                'description' => 'AI ช่วยร่างคอนเทนต์ แคปชันโพสต์ บล็อก สคริปต์ และคำโฆษณา',
                'order' => 5,
            ],
            [
                'name' => 'Research & Analysis',
                'name_th' => 'ค้นคว้า & สรุปข้อมูล',
                'slug' => 'research',
                'icon' => 'search',
                'description' => 'AI สรุปเอกสาร PDF ค้นคว้างานวิจัย สรุปเนื้อหายาว และวิเคราะห์ข้อมูล',
                'order' => 6,
            ],
            [
                'name' => 'Chatbots & Assistants',
                'name_th' => 'แชทบอท & ผู้ช่วยอเนกประสงค์',
                'slug' => 'chat',
                'icon' => 'message-square',
                'description' => 'โมเดลภาษา LLM อัจฉริยะ ตอบคำถาม วางแผนงาน และแก้ปัญหาทุกรูปแบบ',
                'order' => 7,
            ],
            [
                'name' => 'Productivity & Automation',
                'name_th' => 'เพิ่มผลผลิต & ทำงานอัตโนมัติ',
                'slug' => 'productivity',
                'icon' => 'zap',
                'description' => 'สร้างสไลด์นำเสนอ จัดการโน้ต และเชื่อมต่อระบบทำงานอัตโนมัติโดยไม่ต้องเขียนโค้ด',
                'order' => 8,
            ],
        ];

        $categories = [];
        foreach ($categoriesData as $cData) {
            $categories[$cData['slug']] = Category::create($cData);
        }

        $tools = [
            // 1. Coding Tools
            [
                'category_id' => $categories['coding']->id,
                'name' => 'Cursor',
                'slug' => 'cursor',
                'tagline' => 'The AI Code Editor built for pairing with frontier models',
                'tagline_th' => 'โปรแกรมเขียนโค้ด AI ยุคใหม่ เข้าใจโค้ดทั้งโปรเจกต์และแก้บั๊กให้อัตโนมัติ',
                'description' => 'Cursor is a fork of VS Code supercharged with AI. It indexes your entire codebase for multi-file edits, intelligent completions, and interactive terminal command execution.',
                'description_th' => 'Cursor คือโปรแกรมแก้ไขโค้ดที่สร้างบนพื้นฐานของ VS Code เสริมพลังด้วย AI ที่สามารถอ่านและทำความเข้าใจโค้ดทั้งโปรเจกต์ (Codebase Indexing) เขียนโค้ดหลายไฟล์พร้อมกัน ตรวจจับบั๊ก และสั่งรันเทอร์มินัลได้ทันที',
                'logo_url' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&q=80',
                'website_url' => 'https://www.cursor.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free tier / Pro at $20/month',
                'pricing_details_th' => 'ใช้งานฟรี (จำกัดโควต้า) / แบบ Pro $20 ต่อเดือน',
                'features' => ['Composer multi-file editing', 'Chat with your whole codebase', 'Instant bug fixing', 'Terminal assistant'],
                'features_th' => ['แก้ไขโค้ดหลายไฟล์พร้อมกันด้วย Composer', 'แชทถาม-ตอบโค้ดทั้งโปรเจกต์', 'ตรวจจับและแก้บั๊กแบบเรียลไทม์', 'ผู้ช่วยสั่งคำสั่ง Terminal'],
                'tasks' => ['coding', 'web_dev', 'bug_fixing', 'refactoring'],
                'tasks_th' => ['เขียนโค้ด', 'สร้างเว็บ/แอป', 'แก้บั๊กโปรแกรม', 'ปรับปรุงโครงสร้างโค้ด'],
                'strengths' => ['Context-aware multi-file edits', 'VS Code extension compatibility'],
                'best_for' => 'Full-stack software engineers and web developers',
                'best_for_th' => 'โปรแกรมเมอร์และนักพัฒนาเว็บทุกระดับที่ต้องการเพิ่มความเร็วในการเขียนโค้ด 3-5 เท่า',
                'popularity_score' => 99,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['coding']->id,
                'name' => 'v0',
                'slug' => 'v0-vercel',
                'tagline' => 'Generative UI system powered by AI and React/Tailwind',
                'tagline_th' => 'สั่ง AI สร้างหน้าตาเว็บไซต์ (UI Components) สวยงามด้วย React และ Tailwind CSS',
                'description' => 'v0 uses AI to generate copy-paste friendly React components styled with Tailwind CSS and shadcn/ui directly from natural language prompts.',
                'description_th' => 'v0 เป็นเครื่องมือสร้าง UI อัจฉริยะจาก Vercel เพียงแค่พิมพ์บรรยายว่าต้องการหน้าจอหรือฟังก์ชันอะไร AI จะออกแบบและเขียนโค้ด React + Tailwind CSS + shadcn/ui ให้พร้อมก๊อปปี้ไปใช้งานได้ทันที',
                'logo_url' => 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=128&q=80',
                'website_url' => 'https://v0.dev',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free plan with monthly credits / Premium available',
                'pricing_details_th' => 'มีเครดิตฟรีทุกเดือน / มีแพ็กเกจพรีเมียม',
                'features' => ['Prompt to React component', 'Instant live preview', 'Figma to Code workflow', 'Tailwind & Shadcn support'],
                'features_th' => ['พิมพ์สั่งเพื่อสร้าง React Components', 'พรีวิวผลลัพธ์แบบโต้ตอบได้ทันที', 'แปลงไอเดียเป็นหน้าเว็บสวยงาม', 'รองรับ Tailwind CSS และ shadcn/ui'],
                'tasks' => ['web_dev', 'ui_design', 'frontend'],
                'tasks_th' => ['สร้างเว็บ/แอป', 'ออกแบบหน้าจอ UI', 'เขียน Frontend'],
                'strengths' => ['Pixel-perfect modern aesthetics', 'Clean reusable code output'],
                'best_for' => 'Frontend developers and designers building modern UI interfaces',
                'best_for_th' => 'นักพัฒนา Frontend และ Designer ที่ต้องการสร้าง UI สวยงามอย่างรวดเร็ว',
                'popularity_score' => 95,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['coding']->id,
                'name' => 'GitHub Copilot',
                'slug' => 'github-copilot',
                'tagline' => 'Your AI pair programmer integrated into popular IDEs',
                'tagline_th' => 'ผู้ช่วยเขียนโค้ดคู่ใจใน VS Code, IntelliJ และเครื่องมือพัฒนาชั้นนำ',
                'description' => 'GitHub Copilot turns natural language into code autocomplete suggestions inside your favorite code editor, trained on billions of lines of public code.',
                'description_th' => 'ผู้ช่วยเขียนโค้ดตัวแรกๆ ของโลกที่เชื่อมต่อกับ IDE โดยตรง ช่วยเติมโค้ดอัตโนมัติ (Autocomplete) เขียนฟังก์ชัน และเขียน Unit Tests ได้อย่างแม่นยำ',
                'logo_url' => 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=128&q=80',
                'website_url' => 'https://github.com/features/copilot',
                'pricing_type' => 'paid',
                'pricing_details' => '$10/month (Free for verified students and OSS maintainers)',
                'pricing_details_th' => '$10 ต่อเดือน (ฟรีสำหรับนักศึกษาและผู้ดูแล Open Source)',
                'features' => ['Real-time code completion', 'In-editor chat', 'CLI assistant', 'Test generation'],
                'features_th' => ['เติมโค้ดอัตโนมัติขณะพิมพ์', 'แชทสอบถามใน Editor', 'ช่วยเขียนคำสั่ง CLI', 'เจนเนอเรต Unit Test'],
                'tasks' => ['coding', 'autocompletion', 'unit_testing'],
                'tasks_th' => ['เขียนโค้ด', 'เติมโค้ดอัตโนมัติ', 'เขียน Test'],
                'strengths' => ['Seamless IDE integration', 'Fast inline suggestions'],
                'best_for' => 'Day-to-day coding speed in existing large repositories',
                'best_for_th' => 'นักพัฒนาที่ต้องการตัวช่วยเติมโค้ดให้พิมพ์งานได้เร็วขึ้น',
                'popularity_score' => 92,
                'is_featured' => false,
            ],
            [
                'category_id' => $categories['coding']->id,
                'name' => 'Bolt.new',
                'slug' => 'bolt-new',
                'tagline' => 'Prompt, build, and deploy full-stack web applications in browser',
                'tagline_th' => 'สั่งสร้างเว็บแอปพลิเคชันแบบ Full-stack และรันสดในเบราว์เซอร์ได้ทันที',
                'description' => 'Bolt.new allows developers to prompt, build, edit, and deploy full-stack Node.js web applications directly inside a browser sandbox without local setup.',
                'description_th' => 'แพลตฟอร์มสร้างแอป Full-stack บนเบราว์เซอร์ เพียงพิมพ์อธิบายระบบ AI จะติดตั้งแพ็กเกจ npm เขียนทั้ง Frontend & Backend และรันเซิร์ฟเวอร์จำลองให้ทดสอบได้ทันที',
                'logo_url' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=128&q=80',
                'website_url' => 'https://bolt.new',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free tier available / Pro plans',
                'pricing_details_th' => 'มีแพ็กเกจฟรี / มีแพ็กเกจ Pro สำหรับงานขนาดใหญ่',
                'features' => ['Full-stack Node runtime in browser', 'Instant Netlify/Vercel deployment', 'Multi-file generation', 'Live error fixing'],
                'features_th' => ['รัน Full-stack ในเบราว์เซอร์', 'Deploy ขึ้นเว็บได้ในคลิกเดียว', 'สร้างระบบหลายไฟล์พร้อมกัน', 'แก้ปัญหา Runtime Error อัตโนมัติ'],
                'tasks' => ['coding', 'web_dev', 'fullstack_app', 'prototyping'],
                'tasks_th' => ['เขียนโค้ด', 'สร้างเว็บ/แอป', 'ทำเว็บแอปรวดเร็ว', 'สร้างต้นแบบ Prototype'],
                'strengths' => ['Zero setup in-browser execution', 'Instant production deployment'],
                'best_for' => 'Rapid prototyping and launching MVPs in minutes',
                'best_for_th' => 'ผู้ที่ต้องการสร้าง MVP หรือต้นแบบเว็บแอปพลิเคชันให้เสร็จภายในไม่กี่นาที',
                'popularity_score' => 94,
                'is_featured' => true,
            ],

            // 2. Image & Art
            [
                'category_id' => $categories['image']->id,
                'name' => 'Midjourney',
                'slug' => 'midjourney',
                'tagline' => 'The premier generative AI for stunning, photorealistic visuals',
                'tagline_th' => 'เครื่องมือสร้างภาพ AI ระดับท็อป ภาพสมจริง แสงเงาและสุนทรียภาพระดับมาสเตอร์พีซ',
                'description' => 'Midjourney produces breathtaking photorealistic and artistic images from textual prompts, famous for unparalleled aesthetic quality, lighting, and detail.',
                'description_th' => 'สุดยอด AI สร้างภาพที่ให้คุณภาพแสงเงา องค์ประกอบ และความสมจริงระดับแนวหน้าของวงการ เหมาะสำหรับงานภาพถ่าย แฟชั่น โปสเตอร์ และงานอาร์ตระดับสูง',
                'logo_url' => 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=128&q=80',
                'website_url' => 'https://www.midjourney.com',
                'pricing_type' => 'paid',
                'pricing_details' => 'Starting from $10/month',
                'pricing_details_th' => 'เริ่มต้น $10 ต่อเดือน (ไม่มี Free tier ถาวร)',
                'features' => ['Photorealistic v6 model', 'Web editor & inpainting', 'Style reference & character consistency', 'Pan & Zoom controls'],
                'features_th' => ['โมเดล v6 ความสมจริงสูงสุด', 'เว็บสร้างภาพและ Inpainting แก้เฉพาะจุด', 'ควบคุมสไตล์และคาแรคเตอร์ตัวละครเดิม', 'ปรับมุมกล้อง Pan & Zoom'],
                'tasks' => ['image_gen', 'concept_art', 'graphic_design', 'photography'],
                'tasks_th' => ['สร้างภาพ AI', 'งานคอนเซ็ปต์อาร์ต', 'กราฟิกดีไซน์', 'ภาพถ่ายเสมือนจริง'],
                'strengths' => ['Highest aesthetic quality', 'Realistic textures and lighting'],
                'best_for' => 'Creative directors, artists, and marketing designers',
                'best_for_th' => 'ดีไซเนอร์ ศิลปิน และนักการตลาดที่ต้องการภาพคุณภาพสูงระดับมืออาชีพ',
                'popularity_score' => 98,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['image']->id,
                'name' => 'Flux',
                'slug' => 'flux-1',
                'tagline' => 'State-of-the-art open-weight image model by Black Forest Labs',
                'tagline_th' => 'โมเดลสร้างภาพ AI ยุคใหม่ สะกดตัวอักษรในภาพเป๊ะ และสรีระนิ้วมือสมบูรณ์แบบ',
                'description' => 'FLUX.1 is a 12-billion parameter flow-transformer model excelling in prompt adherence, typography generation inside images, and anatomical realism.',
                'description_th' => 'โมเดลสร้างภาพตัวท็อปจากผู้สร้าง Stable Diffusion เดิม โดดเด่นเรื่องการทำตาม Prompt อย่างแม่นยำมาก วาดตัวอักษรภาษาอังกฤษในภาพได้คมชัด และวาดมือ/นิ้วได้สมจริง',
                'logo_url' => 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=128&q=80',
                'website_url' => 'https://blackforestlabs.ai',
                'pricing_type' => 'open_source',
                'pricing_details' => 'Open weights (Schnell/Dev) / Pro API',
                'pricing_details_th' => 'เปิด Open-source ให้โหลดรันเองได้ฟรี / มีบริการ Cloud API',
                'features' => ['12B parameter architecture', 'Flawless text typography in pictures', 'Accurate anatomy & fingers', 'Open weights available'],
                'features_th' => ['โครงสร้าง 12 พันล้านพารามิเตอร์', 'สะกดตัวอักษรบนป้ายและเสื้อผ้าได้เป๊ะ', 'วาดสรีระและมือได้อย่างแม่นยำ', 'มีเวอร์ชัน Open-weight รันในเครื่องได้'],
                'tasks' => ['image_gen', 'text_in_image', 'open_source_ai'],
                'tasks_th' => ['สร้างภาพ AI', 'ใส่ข้อความในภาพ', 'รันโมเดลเองฟรี'],
                'strengths' => ['Typography accuracy', 'High prompt precision', 'Open license available'],
                'best_for' => 'Designers needing readable text on labels/posters and AI power users',
                'best_for_th' => 'ผู้ที่ต้องการสร้างภาพที่มีข้อความคมชัด โลโก้ และผู้ที่ต้องการรัน AI บนเครื่องตัวเอง',
                'popularity_score' => 96,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['image']->id,
                'name' => 'Leonardo',
                'slug' => 'leonardo-ai',
                'tagline' => 'All-in-one AI creative suite for assets, textures, and illustrations',
                'tagline_th' => 'สตูดิโอสร้างภาพและกราฟิก 2D/3D ครบวงจร ใช้งานง่าย มีเครดิตฟรีทุกวัน',
                'description' => 'Leonardo.Ai provides a comprehensive web app for generating game assets, concept art, photorealistic portraits, and motion videos with high fine-tuning control.',
                'description_th' => 'แพลตฟอร์มสร้างภาพกราฟิกที่มีฟีเจอร์ครบครัน ทั้งการสร้าง Asset สำหรับเกม ปรับแต่งภาพ ลบพื้นหลัง แปลงภาพนิ่งเป็นวิดีโอ และมีเครดิตฟรีรีเซ็ตให้ทุกวัน',
                'logo_url' => 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=128&q=80',
                'website_url' => 'https://leonardo.ai',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free 150 daily tokens / Premium plans',
                'pricing_details_th' => 'ฟรี 150 โทเค็นทุกวัน / มีแพ็กเกจพรีเมียม',
                'features' => ['150 free daily tokens', 'Realtime canvas editing', 'Universal Upscaler', 'Motion animation generator'],
                'features_th' => ['รับ 150 โทเค็นฟรีทุกวัน', 'กระดานวาดภาพ Realtime Canvas', 'ขยายภาพให้คมชัดขั้นสูง (Upscale)', 'แปลงภาพนิ่งเป็นวิดีโอสั้น'],
                'tasks' => ['image_gen', 'game_assets', 'graphic_design', 'image_upscaling'],
                'tasks_th' => ['สร้างภาพ AI', 'สร้าง Asset เกม', 'งานกราฟิก', 'ขยายภาพให้ชัด'],
                'strengths' => ['Generous free daily allowance', 'User-friendly web canvas UI'],
                'best_for' => 'Game developers, graphic designers, and social media creators',
                'best_for_th' => 'นักทำเกม นักออกแบบกราฟิก และครีเอเตอร์ที่ต้องการเครื่องมือใช้งานง่ายและมีโควต้าฟรี',
                'popularity_score' => 90,
                'is_featured' => false,
            ],
            [
                'category_id' => $categories['image']->id,
                'name' => 'Canva',
                'slug' => 'canva-magic-studio',
                'tagline' => 'AI-powered design suite for social media, presentations, and marketing',
                'tagline_th' => 'ชุดเครื่องมือ AI ใน Canva ช่วยออกแบบสไลด์ กราฟิกโซเชียลมีเดีย และลบวัตถุในคลิกเดียว',
                'description' => 'Canva Magic Studio integrates generative design, AI text-to-image, magic expand, background removal, and instant slide generation into the popular Canva platform.',
                'description_th' => 'ระบบ AI อัจฉริยะใน Canva ที่ช่วยขยายรูปภาพ (Magic Expand) ลบวัตถุที่ไม่ต้องการ (Magic Eraser) สร้างภาพกราฟิกจากคำสั่ง และสร้างสไลด์หรือพรีเซนเทชันอัตโนมัติ',
                'logo_url' => 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=128&q=80',
                'website_url' => 'https://www.canva.com/magic-studio/',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free tier available / Canva Pro',
                'pricing_details_th' => 'ใช้งานฟรีบางส่วน / Canva Pro สำหรับเครื่องมือ AI เต็มรูปแบบ',
                'features' => ['Magic Eraser & Background Remover', 'Magic Expand image edges', 'Magic Design for presentations', 'AI Copywriter'],
                'features_th' => ['ลบพื้นหลังและลบวัตถุเนียนกริบ', 'ขยายขอบภาพให้กว้างขึ้น', 'ออกแบบสไลด์และโพสต์อัตโนมัติ', 'AI ช่วยเขียนข้อความโฆษณา'],
                'tasks' => ['graphic_design', 'social_media', 'presentation', 'photo_editing'],
                'tasks_th' => ['งานกราฟิก', 'ทำคอนเทนต์โซเชียล', 'สร้างสไลด์นำเสนอ', 'แต่งรูปภาพ'],
                'strengths' => ['Extremely easy to use', 'All-in-one publishing workflow'],
                'best_for' => 'Marketers, teachers, and small business owners',
                'best_for_th' => 'นักการตลาด แม่ค้าออนไลน์ ครู และผู้ประกอบการที่ต้องการงานกราฟิกด่วนสวยงาม',
                'popularity_score' => 93,
                'is_featured' => false,
            ],

            // 3. Video & Animation
            [
                'category_id' => $categories['video']->id,
                'name' => 'Runway',
                'slug' => 'runway-gen-3',
                'tagline' => 'Hollywood-grade generative video for cinematic motion and storytelling',
                'tagline_th' => 'AI สร้างภาพยนตร์และวิดีโอระดับฮอลลีวูด เคลื่อนไหวลื่นไหล สมจริงอย่างน่าทึ่ง',
                'description' => 'Runway Gen-3 Alpha is an industry-leading video generation model capable of creating photorealistic cinematic scenes with precise motion control and physics.',
                'description_th' => 'สุดยอด AI สร้างวิดีโอจาก Runway ที่ให้ความคมชัดระดับภาพยนตร์ สามารถสร้างวิดีโอจากข้อความ (Text-to-Video) หรือแปลงภาพนิ่งให้เคลื่อนไหว (Image-to-Video) พร้อมควบคุมมุมกล้องได้อย่างแม่นยำ',
                'logo_url' => 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=128&q=80',
                'website_url' => 'https://runwayml.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free trial credits / Standard $12/month',
                'pricing_details_th' => 'ทดลองฟรีพร้อมเครดิตเริ่มต้น / รายเดือนเริ่มต้น $12',
                'features' => ['Gen-3 Alpha cinematic video', 'Motion brush camera control', 'Lip sync audio matching', 'Inpainting on video'],
                'features_th' => ['เจนวิดีโอความละเอียดสูงระดับหนังโรง', 'ควบคุมทิศทางและการเคลื่อนไหวด้วย Motion Brush', 'ขยับปากพูดตามเสียงพากย์ (Lip Sync)', 'ลบหรือแก้ไขวัตถุในวิดีโอ'],
                'tasks' => ['video_gen', 'cinematic_vfx', 'animation'],
                'tasks_th' => ['สร้างวิดีโอ AI', 'เอฟเฟกต์ภาพยนตร์', 'สร้างแอนิเมชัน'],
                'strengths' => ['Hollywood film quality', 'Advanced camera physics simulation'],
                'best_for' => 'Filmmakers, VFX artists, and high-end video producers',
                'best_for_th' => 'ผู้กำกับ คนทำคอนเทนต์วิดีโอ และสตูดิโอโปรดักชันที่ต้องการคลิปคุณภาพสูง',
                'popularity_score' => 97,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['video']->id,
                'name' => 'Kling',
                'slug' => 'kling-ai',
                'tagline' => 'High-definition 1080p AI video generation up to 2 minutes long',
                'tagline_th' => 'AI เจนวิดีโอ Full HD ความยาวสูงสุดถึง 2 นาที พร้อมระบบจำลองฟิสิกส์สมจริง',
                'description' => 'Kling AI creates ultra-realistic videos with intricate physics simulations, supporting full 1080p resolution and extending shots up to 2 minutes with strong coherence.',
                'description_th' => 'AI เจนวิดีโอที่กำลังมาแรง โดดเด่นเรื่องการขยับท่าทางของคนและสัตว์ที่ถูกต้องตามหลักฟิสิกส์ รองรับความละเอียดระดับ 1080p และสามารถต่อขยายคลิปได้ยาวต่อเนื่อง',
                'logo_url' => 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=128&q=80',
                'website_url' => 'https://klingai.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Daily free login points / Pro subscription',
                'pricing_details_th' => 'รับพอยท์ฟรีทุกวันที่ล็อกอิน / มีแพ็กเกจ Pro สำหรับเจนวิดีโอไม่อั้น',
                'features' => ['Up to 2-minute video generation', '1080p HD output', 'Accurate fluid & motion physics', 'Text-to-Video & Image-to-Video'],
                'features_th' => ['สร้างวิดีโอยาวต่อเนื่องสูงสุด 2 นาที', 'ความละเอียดสูง 1080p', 'การเคลื่อนไหวและการไหลของน้ำสมจริง', 'แปลงทั้งข้อความและรูปภาพเป็นวิดีโอ'],
                'tasks' => ['video_gen', 'social_video', 'advertising'],
                'tasks_th' => ['สร้างวิดีโอ AI', 'ทำคลิป Reels/TikTok', 'ทำโฆษณาสินค้า'],
                'strengths' => ['Long video durations', 'Generous daily free credits'],
                'best_for' => 'TikTok/Reels creators and digital ad agencies',
                'best_for_th' => 'ครีเอเตอร์ทำคลิปสั้น TikTok, Instagram Reels, YouTube Shorts และงานโฆษณา',
                'popularity_score' => 94,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['video']->id,
                'name' => 'HeyGen',
                'slug' => 'heygen',
                'tagline' => 'AI avatar video generator and studio-grade voice translation',
                'tagline_th' => 'สร้างวิดีโอคนพากย์ดิจิทัล (AI Avatar) และแปลภาษาปากตรงเสียงเนียนกริบ',
                'description' => 'HeyGen enables users to create professional spokesperson videos without cameras or actors, with custom digital twins and flawless multi-language video dubbing.',
                'description_th' => 'เปลี่ยนสคริปต์ข้อความเป็นวิดีโอคนพูดนำเสนออย่างเป็นธรรมชาติ มีตัวละคร Avatar ให้เลือกนับร้อย พร้อมฟีเจอร์แปลภาษาในวิดีโอให้ขยับปากตรงกับภาษาใหม่ (Video Translate)',
                'logo_url' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&q=80',
                'website_url' => 'https://www.heygen.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free 1 credit trial / Creator starting at $24/mo',
                'pricing_details_th' => 'ทดลองฟรี 1 เครดิต / แบบ Creator เริ่มต้น $24 ต่อเดือน',
                'features' => ['300+ realistic AI avatars', 'Video translation with LipSync', 'Custom avatar creation', 'Instant script generation'],
                'features_th' => ['ตัวละคร AI Avatar เสมือนจริงกว่า 300 แบบ', 'แปลภาษาวิดีโอพร้อมขยับปากตรงภาษา', 'สร้าง Avatar หน้าตัวเองได้', 'AI ช่วยเขียนสคริปต์พูด'],
                'tasks' => ['avatar_video', 'video_translation', 'corporate_training', 'presentations'],
                'tasks_th' => ['สร้าง AI Avatar', 'แปลภาษาวิดีโอ', 'ทำคลิปสอน/อบรม', 'พรีเซนต์สินค้า'],
                'strengths' => ['Uncanny lip-sync precision', 'No camera or microphone required'],
                'best_for' => 'Corporate training, multilingual marketing, and course creators',
                'best_for_th' => 'องค์กรที่ทำวิดีโอเทรนนิ่ง ผู้ผลิตคอร์สออนไลน์ และการตลาดข้ามชาติ',
                'popularity_score' => 91,
                'is_featured' => false,
            ],

            // 4. Voice & Audio
            [
                'category_id' => $categories['audio']->id,
                'name' => 'ElevenLabs',
                'slug' => 'elevenlabs',
                'tagline' => 'The world leader in natural AI voice generation and voice cloning',
                'tagline_th' => 'AI เสียงพากย์อันดับ 1 ของโลก โคลนนิ่งเสียงสมจริง มีอารมณ์ และเป็นธรรมชาติที่สุด',
                'description' => 'ElevenLabs delivers the most expressive, lifelike AI voice synthesis across 30+ languages, with voice cloning, sound effects generation, and conversational agents.',
                'description_th' => 'ผู้นำด้านเสียง AI ที่ให้ความรู้สึกเป็นธรรมชาติ มีน้ำเสียงและอารมณ์เหมือนคนพูดจริง สามารถโคลนเสียงตัวเองจากคลิปสั้นๆ สร้างเสียงเอฟเฟกต์ (SFX) และรองรับภาษาไทยได้อย่างชัดเจน',
                'logo_url' => 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=128&q=80',
                'website_url' => 'https://elevenlabs.io',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free 10,000 characters/month / Starter from $5/mo',
                'pricing_details_th' => 'ฟรี 10,000 ตัวอักษรต่อเดือน / เริ่มต้นเพียง $5 ต่อเดือน',
                'features' => ['Emotional Text-to-Speech', 'Voice cloning from 1-minute audio', 'AI sound effects generator', '30+ languages supported'],
                'features_th' => ['อ่านข้อความเป็นเสียงพากย์ที่มีอารมณ์', 'โคลนเสียงคนได้จากไฟล์เสียง 1 นาที', 'สร้างเสียง Sound Effects จากข้อความ', 'รองรับกว่า 30 ภาษารวมถึงภาษาไทย'],
                'tasks' => ['voiceover', 'voice_cloning', 'audiobook', 'sound_effects'],
                'tasks_th' => ['พากย์เสียง AI', 'โคลนเสียงคน', 'ทำหนังสือเสียง Audiobook', 'สร้างเสียงเอฟเฟกต์'],
                'strengths' => ['Indistinguishable from real human voices', 'Precise inflection and pacing control'],
                'best_for' => 'Podcasters, YouTubers, audiobook publishers, and game studios',
                'best_for_th' => 'ยูทูบเบอร์ นักพากย์ ผู้ทำ Podcast หนังสือเสียง และนักพัฒนาเกม',
                'popularity_score' => 98,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['audio']->id,
                'name' => 'Suno',
                'slug' => 'suno-ai',
                'tagline' => 'Create full radio-ready songs with vocals and instruments in any genre',
                'tagline_th' => 'แต่งเพลงเต็มเพลงพร้อมเสียงร้องและดนตรีทุกแนว เพียงแค่พิมพ์คำบรรยาย',
                'description' => 'Suno allows anyone to produce full songs with vocals, lyrics, and intricate multi-instrument arrangements in any genre from rock, pop, hip-hop to classical.',
                'description_th' => 'AI แต่งเพลงปฏิวัติวงการ เพียงพิมพ์บอกแนวเพลง เช่น "เพลงป๊อปไทยฟังสบายเกี่ยวกับกาแฟยามเช้า" Suno จะแต่งทำนอง เรียบเรียงดนตรี เขียนเนื้อเพลง และร้องให้ออกมาเป็นเพลงสมบูรณ์แบบ',
                'logo_url' => 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=128&q=80',
                'website_url' => 'https://suno.com',
                'pricing_type' => 'freemium',
                'pricing_details' => '50 free daily credits (10 songs) / Pro $10/mo',
                'pricing_details_th' => 'ฟรี 50 เครดิตทุกวัน (สร้างได้ประมาณ 10 เพลง) / Pro $10 ต่อเดือน',
                'features' => ['Full song generation with vocals', 'Lyrics generation or custom lyrics', 'Covers and stems separation', 'Every music genre supported'],
                'features_th' => ['แต่งเพลงเต็มพร้อมเสียงร้องและดนตรี', 'AI ช่วยแต่งเนื้อร้องหรือใส่เนื้อเองได้', 'แยกแทร็กดนตรีและเสียงร้อง', 'รองรับทุกแนวเพลงทั่วโลก'],
                'tasks' => ['music_generation', 'songwriting', 'jingles', 'background_music'],
                'tasks_th' => ['แต่งเพลง AI', 'เขียนเนื้อเพลง', 'ทำเพลงจิงเกิลโฆษณา', 'ทำเพลงประกอบคลิป'],
                'strengths' => ['Incredible musicality and vocal hooks', 'Free daily credits'],
                'best_for' => 'Content creators needing original background music and aspiring musicians',
                'best_for_th' => 'ครีเอเตอร์ที่ต้องการเพลงประกอบคลิปไม่ติดลิขสิทธิ์ และผู้ที่อยากแต่งเพลงของตัวเอง',
                'popularity_score' => 97,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['audio']->id,
                'name' => 'Udio',
                'slug' => 'udio',
                'tagline' => 'High-fidelity music creation with unprecedented vocal nuance',
                'tagline_th' => 'สร้างสรรค์บทเพลงคุณภาพเสียงระดับสตูดิโอ พร้อมการร้องที่เปี่ยมด้วยอารมณ์',
                'description' => 'Udio creates studio-quality music tracks with nuanced vocal delivery, customizable intros, outros, and seamless verse extensions.',
                'description_th' => 'อีกหนึ่ง AI แต่งเพลงชั้นแนวหน้าที่ให้คุณภาพมิกซ์เสียงและเสียงร้องระดับสตูดิโออัดเสียง สามารถควบคุมท่อน Intro, Outro และต่อเพลงได้อย่างประณีต',
                'logo_url' => 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=128&q=80',
                'website_url' => 'https://www.udio.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free credits monthly / Standard from $10/mo',
                'pricing_details_th' => 'มีเครดิตฟรีให้ทดลอง / แพ็กเกจ Standard $10 ต่อเดือน',
                'features' => ['Studio-grade audio fidelity', 'Extend & remix songs', 'Custom prompt tag system', 'Vocal emotion control'],
                'features_th' => ['ความคมชัดระดับห้องอัดสตูดิโอ', 'ต่อเพลงและรีมิกซ์ได้ไม่จำกัด', 'ระบบแท็กควบคุมแนวเพลงละเอียด', 'ถ่ายทอดอารมณ์เสียงร้องได้หลากหลาย'],
                'tasks' => ['music_generation', 'remixing', 'soundtracks'],
                'tasks_th' => ['แต่งเพลง AI', 'รีมิกซ์เพลง', 'ทำเพลงประกอบภาพยนตร์'],
                'strengths' => ['Studio mastering quality', 'Fine-grained track control'],
                'best_for' => 'Music producers and creators looking for deep track customization',
                'best_for_th' => 'โปรดิวเซอร์เพลงและผู้ที่ต้องการปรับแต่งโครงสร้างเพลงอย่างละเอียด',
                'popularity_score' => 89,
                'is_featured' => false,
            ],

            // 5. Writing & Marketing
            [
                'category_id' => $categories['writing']->id,
                'name' => 'Claude',
                'slug' => 'claude-3-7-sonnet',
                'tagline' => 'The world’s top model for deep hybrid reasoning, writing, and coding',
                'tagline_th' => 'โมเดล AI ที่เก่งที่สุดในการคิดวิเคราะห์เชิงลึก เขียนสำนวนสละสลวย และเขียนโค้ดขั้นเทพ',
                'description' => 'Claude from Anthropic is a breakthrough hybrid reasoning model combining instant responses with extended thinking for complex problem solving, creative writing, and system architecture.',
                'description_th' => 'โมเดล AI ชั้นนำระดับโลกจาก Anthropic ที่โดดเด่นทั้งการใช้ภาษาอย่างเป็นธรรมชาติ สละสลวยเหมือนมนุษย์เขียน มีระบบ Hybrid Extended Thinking วิเคราะห์โจทย์ยากๆ ซับซ้อน และเขียนโค้ดได้อย่างแม่นยำสูงมาก',
                'logo_url' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&q=80',
                'website_url' => 'https://claude.ai',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free access available / Claude Pro $20/month',
                'pricing_details_th' => 'ใช้งานฟรี (จำกัดข้อความ) / Claude Pro $20 ต่อเดือน',
                'features' => ['Extended thinking mode', '200K token context window', 'Artifacts interactive preview', 'Human-like eloquent prose'],
                'features_th' => ['โหมดคิดเชิงลึก Extended Thinking', 'รองรับบริบทขนาดยาว 200,000 โทเค็น', 'ระบบ Artifacts พรีวิวโค้ดและเอกสารสด', 'สำนวนภาษาไทยและอังกฤษสละสลวยเป็นเลิศ'],
                'tasks' => ['writing', 'coding', 'research', 'analysis', 'brainstorming'],
                'tasks_th' => ['เขียนบทความ', 'เขียนโค้ด', 'วิเคราะห์ข้อมูลเชิงลึก', 'ระดมสมอง & วางแผน'],
                'strengths' => ['Nuanced human-level writing tone', 'Exceptional coding and mathematical reasoning'],
                'best_for' => 'Writers, researchers, software architects, and knowledge workers',
                'best_for_th' => 'นักเขียน นักวิจัย โปรแกรมเมอร์ และทุกคนที่ต้องการงานเขียนและการวิเคราะห์คุณภาพสูงสุด',
                'popularity_score' => 100,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['writing']->id,
                'name' => 'ChatGPT',
                'slug' => 'chatgpt-gpt-4o',
                'tagline' => 'The ubiquitous multimodal AI assistant for conversation, analysis, and creation',
                'tagline_th' => 'ผู้ช่วย AI อเนกประสงค์ยอดนิยมอันดับ 1 ฉลาดรอบด้าน วิเคราะห์ภาพ เสียง และเอกสาร',
                'description' => 'ChatGPT powered by OpenAI is the flagship conversational intelligence, offering real-time voice, vision inspection, web browsing, data analysis, and image generation.',
                'description_th' => 'แชทบอท AI ที่ได้รับความนิยมมากที่สุดในโลก จาก OpenAI รองรับทั้งการพิมพ์คุย สั่งงานด้วยเสียง วิเคราะห์รูปภาพและไฟล์ Excel สร้างภาพกราฟิกด้วย DALL-E 3 และค้นหาข้อมูลจากอินเทอร์เน็ตสดๆ',
                'logo_url' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=128&q=80',
                'website_url' => 'https://chatgpt.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free tier / Plus $20/month / Pro $200/month',
                'pricing_details_th' => 'ใช้งานฟรี / Plus $20 ต่อเดือน / Pro สำหรับสายวิจัยขั้นสูง',
                'features' => ['Multimodal Voice & Vision', 'Advanced Data Analysis (Python execution)', 'Custom GPTs marketplace', 'Real-time Web Browsing'],
                'features_th' => ['สนทนาด้วยเสียงแบบเรียลไทม์และดูภาพ', 'วิเคราะห์ข้อมูลและรันโค้ด Python ในตัว', 'คลังสร้าง GPTs ปรับแต่งเฉพาะตัว', 'ค้นหาข้อมูลเว็บไซต์แบบสดๆ'],
                'tasks' => ['chatting', 'writing', 'data_analysis', 'general_tasks'],
                'tasks_th' => ['แชทถามตอบ', 'เขียนบทความ', 'วิเคราะห์ตารางข้อมูล', 'งานทั่วไปทุกรูปแบบ'],
                'strengths' => ['Broadest ecosystem and tool integrations', 'Great real-time voice mode'],
                'best_for' => 'General public, students, professionals, and teams',
                'best_for_th' => 'ทุกคนที่ต้องการผู้ช่วยอัจฉริยะข้างกายสำหรับทำงาน เรียน และแก้ปัญหาในชีวิตประจำวัน',
                'popularity_score' => 100,
                'is_featured' => true,
            ],

            // 6. Research & Analysis
            [
                'category_id' => $categories['research']->id,
                'name' => 'Perplexity',
                'slug' => 'perplexity-ai',
                'tagline' => 'The conversational search engine delivering cited, verified answers',
                'tagline_th' => 'เครื่องมือค้นหาข้อมูลยุคใหม่ สรุปคำตอบพร้อมอ้างอิงแหล่งที่มาแม่นยำ ไม่มั่ว',
                'description' => 'Perplexity is an AI-powered search engine that answers questions directly by summarizing live web sources with clickable footnotes and citations.',
                'description_th' => 'ระบบค้นหาข้อมูลที่ผสานพลัง AI ค้นหาเว็บหลายสิบหน้าพร้อมกันแล้วนำมาเรียบเรียงเป็นคำตอบที่กระชับ ตรงประเด็น พร้อมลิงก์อ้างอิงแหล่งข่าวและเปเปอร์วิชาการทุกประโยค',
                'logo_url' => 'https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?w=128&q=80',
                'website_url' => 'https://www.perplexity.ai',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free tier / Pro at $20/month',
                'pricing_details_th' => 'ใช้งานฟรี / Pro $20 ต่อเดือน',
                'features' => ['Direct citations and source links', 'Pro Search with deep web research', 'File upload and analysis', 'Focus search (Academic, YouTube, Reddit)'],
                'features_th' => ['แสดงแหล่งที่มาและอ้างอิงชัดเจน', 'โหมด Pro Search ค้นคว้าเชิงลึกหลายมิติ', 'อัปโหลดไฟล์เอกสารเพื่อสรุป', 'ตัวกรองค้นหาเฉพาะ Academic, YouTube, Reddit'],
                'tasks' => ['research', 'web_search', 'fact_checking', 'summarization'],
                'tasks_th' => ['ค้นคว้าข้อมูล', 'ค้นหาเว็บอัจฉริยะ', 'ตรวจสอบข้อเท็จจริง', 'สรุปเนื้อหายาว'],
                'strengths' => ['Zero hallucination citations', 'Up-to-the-minute web freshness'],
                'best_for' => 'Students, journalists, researchers, and market analysts',
                'best_for_th' => 'นักศึกษา นักวิจัย นักข่าว และผู้ที่ต้องการข้อมูลที่ถูกต้องเชื่อถือได้พร้อมที่มา',
                'popularity_score' => 97,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['research']->id,
                'name' => 'DeepSeek',
                'slug' => 'deepseek-r1',
                'tagline' => 'Open-weights reasoning model matching top closed frontier systems',
                'tagline_th' => 'โมเดล AI สายคิดวิเคราะห์แบบ Open-source ประสิทธิภาพสูงเทียบชั้นโมเดลชั้นนำ',
                'description' => 'DeepSeek is an open reasoning model using reinforcement learning to think through complex math, logic puzzles, and algorithmic code with transparent reasoning traces.',
                'description_th' => 'โมเดล AI ด้านการคิดวิเคราะห์ (Reasoning) ระดับโลกที่เปิดให้ใช้งานและดาวน์โหลดฟรี โดดเด่นด้านคณิตศาสตร์ วิทยาศาสตร์ ตรรกะ และการเขียนอัลกอริทึม โดยแสดงขั้นตอนความคิด (Chain-of-thought) ให้เห็นอย่างโปร่งใส',
                'logo_url' => 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=128&q=80',
                'website_url' => 'https://chat.deepseek.com',
                'pricing_type' => 'free',
                'pricing_details' => '100% Free web access & open weights',
                'pricing_details_th' => 'ใช้งานผ่านเว็บฟรี 100% และโหลดไฟล์โมเดลไปรันเองได้ฟรี',
                'features' => ['Visible step-by-step reasoning tokens', 'Competitive with o1 on math benchmarks', 'Extremely low API pricing', 'Open weights on HuggingFace'],
                'features_th' => ['แสดงวิธีคิดเป็นขั้นตอนอย่างละเอียด', 'เก่งคณิตศาสตร์และตรรกะระดับท็อป', 'ราคา API ถูกมากสำหรับนักพัฒนา', 'เปิด Open Source โหลดไปใช้ได้อิสระ'],
                'tasks' => ['math_solving', 'logic_reasoning', 'coding', 'research'],
                'tasks_th' => ['แก้โจทย์คณิตศาสตร์', 'คิดวิเคราะห์เชิงตรรกะ', 'เขียนโค้ดอัลกอริทึม', 'ค้นคว้าวิจัย'],
                'strengths' => ['Outstanding math and reasoning capability', 'Completely free & open source'],
                'best_for' => 'Mathematicians, competitive programmers, and budget-conscious developers',
                'best_for_th' => 'นักคณิตศาสตร์ นักพัฒนาโปรแกรม และผู้ที่ต้องการ AI คุณภาพสูงมากโดยไม่มีค่าใช้จ่าย',
                'popularity_score' => 98,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['research']->id,
                'name' => 'ChatPDF',
                'slug' => 'chatpdf',
                'tagline' => 'Chat with any PDF document, research paper, or textbook instantly',
                'tagline_th' => 'อัปโหลดไฟล์ PDF แล้วแชทถาม-ตอบ สรุปเนื้อหาสำคัญได้ทันที',
                'description' => 'ChatPDF transforms lengthy PDF documents, manuals, and academic papers into interactive conversational partners that answer questions with page references.',
                'description_th' => 'เครื่องมือสรุปเอกสาร PDF เพียงลากไฟล์ใส่ระบบ ก็สามารถพิมพ์ถามคำถาม ให้สรุปใจความสำคัญ หาข้อความเฉพาะ หรืออธิบายหัวข้อยากๆ พร้อมระบุหน้าที่พบข้อมูล',
                'logo_url' => 'https://images.unsplash.com/photo-1568667256549-094345857637?w=128&q=80',
                'website_url' => 'https://www.chatpdf.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free 2 PDFs/day (up to 120 pages) / Plus $5/mo',
                'pricing_details_th' => 'ฟรี 2 ไฟล์ต่อวัน (สูงสุด 120 หน้า) / Plus เพียง $5 ต่อเดือน',
                'features' => ['Instant PDF parsing', 'Page source citations', 'Multi-document comparison', 'Multilingual document support'],
                'features_th' => ['อ่านเอกสาร PDF ได้รวดเร็วในไม่กี่วินาที', 'ระบุเลขหน้าที่พบข้อมูล', 'รองรับเอกสารหลายภาษา', 'สรุปเนื้อหาบทความวิชาการ'],
                'tasks' => ['pdf_summary', 'research', 'study_assistant', 'document_qa'],
                'tasks_th' => ['สรุปเอกสาร PDF', 'ช่วยอ่านงานวิจัย', 'ช่วยอ่านหนังสือสอบ', 'ค้นหาข้อมูลในเอกสาร'],
                'strengths' => ['No installation required', 'Accurate page citations'],
                'best_for' => 'Students reviewing study notes, lawyers, and financial analysts',
                'best_for_th' => 'นักเรียน นักศึกษา ทนายความ และนักวิเคราะห์ที่ต้องอ่านเอกสารยาวๆ เป็นประจำ',
                'popularity_score' => 88,
                'is_featured' => false,
            ],

            // 7. Productivity & Automation
            [
                'category_id' => $categories['productivity']->id,
                'name' => 'Gamma',
                'slug' => 'gamma-app',
                'tagline' => 'Create gorgeous presentations, web pages, and docs in seconds',
                'tagline_th' => 'สร้างสไลด์นำเสนอ เว็บเพจ และเอกสารสวยระดับมือโปรได้ในไม่กี่วินาที',
                'description' => 'Gamma uses AI to generate stunning slide decks, interactive documents, and web pages from a simple text prompt, eliminating hours of PowerPoint formatting.',
                'description_th' => 'เครื่องมือปฏิวัติการทำสไลด์ เพียงพิมพ์หัวข้อหรือใส่โครงร่างเนื้อหา AI จะออกแบบเลย์เอาต์ ใส่รูปภาพ และจัดธีมสีให้ออกมาเป็นสไลด์นำเสนอระดับมืออาชีพพร้อมใช้งานทันที',
                'logo_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=128&q=80',
                'website_url' => 'https://gamma.app',
                'pricing_type' => 'freemium',
                'pricing_details' => '400 free starter credits / Plus at $8/month',
                'pricing_details_th' => 'รับฟรี 400 เครดิตเริ่มต้น / Plus เริ่มต้น $8 ต่อเดือน',
                'features' => ['One-click presentation generation', 'Interactive cards & embeds', 'Export to PowerPoint and PDF', 'Custom brand themes'],
                'features_th' => ['กดคลิกเดียวได้สไลด์ครบชุด', 'แทรกการ์ดและวิดีโอแบบอินเทอร์แอคทีฟ', 'ส่งออกเป็นไฟล์ PowerPoint (.pptx) และ PDF', 'ปรับแต่งธีมสีตามแบรนด์ได้'],
                'tasks' => ['presentation', 'slide_deck', 'web_page', 'pitch_deck'],
                'tasks_th' => ['สร้างสไลด์นำเสนอ', 'ทำ Pitch Deck ขายงาน', 'สร้างหน้าเว็บสั้น', 'จัดทำเอกสารสรุป'],
                'strengths' => ['Modern interactive card format', 'Saves 90% of slide preparation time'],
                'best_for' => 'Startup founders, sales teams, consultants, and educators',
                'best_for_th' => 'ผู้ก่อตั้งสตาร์ทอัพ ทีมเซลส์ ที่ปรึกษา ครู และนักเรียนที่ต้องทำสไลด์เสนองาน',
                'popularity_score' => 96,
                'is_featured' => true,
            ],
            [
                'category_id' => $categories['productivity']->id,
                'name' => 'Notion AI',
                'slug' => 'notion-ai',
                'tagline' => 'Integrated connected workspace AI for notes, tasks, and team wikis',
                'tagline_th' => 'AI ผู้ช่วยใน Notion สรุปโน้ตการประชุม แปลภาษา และดึงข้อมูลจากเอกสารทั้งบริษัท',
                'description' => 'Notion AI sits natively inside your workspace to summarize meeting notes, extract action items, draft proposals, and search your entire company knowledge base.',
                'description_th' => 'ผู้ช่วยอัจฉริยะที่ฝังอยู่ใน Notion ช่วยสรุปบันทึกการประชุม เขียนร่างโครงการ แปลภาษา ตรวจสอบคำผิด และสามารถค้นหาคำตอบจากฐานข้อมูลโน้ตทั้งหมดในทีมของคุณได้ทันที',
                'logo_url' => 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=128&q=80',
                'website_url' => 'https://www.notion.so/product/ai',
                'pricing_type' => 'paid',
                'pricing_details' => '$8 to $10/member/month add-on',
                'pricing_details_th' => '$8 ถึง $10 ต่อคนต่อเดือน (ส่วนเสริมของ Notion)',
                'features' => ['Q&A across entire Notion workspace', 'Automated meeting summaries', 'Action item extraction', 'Grammar correction & tone adjustment'],
                'features_th' => ['ถาม-ตอบข้อมูลจากทุกเอกสารใน Workspace', 'สรุปเนื้อหาการประชุมอัตโนมัติ', 'ดึงรายการสิ่งที่ต้องทำ (To-Do List)', 'ตรวจไวยากรณ์และปรับโทนเสียงข้อความ'],
                'tasks' => ['note_taking', 'team_wiki', 'task_management', 'meeting_summary'],
                'tasks_th' => ['จดโน้ต & จัดการงาน', 'สรุปการประชุม', 'ทำฐานข้อมูลความรู้ในทีม', 'เขียนเอกสารองค์กร'],
                'strengths' => ['Deep workspace context understanding', 'Smooth inline UX'],
                'best_for' => 'Teams and individuals who manage their lives and companies in Notion',
                'best_for_th' => 'ทีมงานและบุคคลที่ใช้ Notion ในการบริหารจัดการงาน โน้ต และโครงการ',
                'popularity_score' => 92,
                'is_featured' => false,
            ],
            [
                'category_id' => $categories['chat']->id,
                'name' => 'Gemini',
                'slug' => 'google-gemini',
                'tagline' => 'Google’s next-gen multimodal intelligence with 1M+ context window',
                'tagline_th' => 'AI มัลติโมดอลจาก Google รองรับบริบทข้อมูลยาวมหาศาล และเชื่อมต่อแอป Google ครบวงจร',
                'description' => 'Gemini offers massive context handling capabilities capable of processing hours of video, entire codebases, and audio recordings with deep integration across Google Workspace.',
                'description_th' => 'โมเดล AI จาก Google ที่รองรับความยาวของข้อมูล (Context Window) ได้ถึง 1-2 ล้านโทเค็น สามารถอ่านวิดีโอยาว 1 ชั่วโมง อ่านเอกสารหนาพันหน้า และทำงานร่วมกับ Gmail, Docs, Drive ได้อย่างแนบเนียน',
                'logo_url' => 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=128&q=80',
                'website_url' => 'https://gemini.google.com',
                'pricing_type' => 'freemium',
                'pricing_details' => 'Free tier available / Gemini Advanced $20/month',
                'pricing_details_th' => 'ใช้งานฟรี / Gemini Advanced $20 ต่อเดือน (รวม Google One 2TB)',
                'features' => ['1M+ token context window', 'Google Workspace extensions', 'Native audio/video understanding', 'Real-time search integration'],
                'features_th' => ['รองรับข้อมูลยาวทะลุ 1 ล้านโทเค็น', 'เชื่อมต่อ Gmail, Google Docs, Drive', 'เข้าใจทั้งภาพ เสียง และวิดีโอ', 'ค้นหาข้อมูลอัปเดตผ่าน Google Search'],
                'tasks' => ['chatting', 'video_analysis', 'large_document_reading', 'workspace_integration'],
                'tasks_th' => ['แชทถามตอบ', 'วิเคราะห์ไฟล์วิดีโอขนาดยาว', 'อ่านเอกสารขนาดใหญ่', 'เชื่อมต่อ Google Workspace'],
                'strengths' => ['Massive 1M+ context window', 'Direct integration with Google ecosystem'],
                'best_for' => 'Users deeply embedded in Google ecosystem and long video/document analysis',
                'best_for_th' => 'ผู้ใช้งาน Google Workspace และผู้ที่ต้องการวิเคราะห์ไฟล์วิดีโอหรือเอกสารขนาดยักษ์',
                'popularity_score' => 95,
                'is_featured' => true,
            ]
        ];

        foreach ($tools as $tool) {
            AiTool::create($tool);
        }
    }
}

